### ISSUE TITLE
components: pagination 

### ISSUE THREAD

**Issue by AugustinMauroy** [ekmas/neobrutalism-components#35]
you should provide a pagination composant

**Comment by ekmas** [comment]
Hey Augustin, actually there is a pagination component: 
https://www.neobrutalism.dev/shadcn/components/pagination

I suppose you meant purely react component (without shadcn). In that case, I won't add it because there is no point in adding it (I would have to spend a lot of time making the component accessible and reusable, and still it wouldn't be good as radix-ui component), you can just use shadcn component and you're good.

**Comment by AugustinMauroy** [comment]
Oh great, thanks. I hadn't realised there was a difference between pure react and shadcn.

**Comment by AugustinMauroy** [comment]
and btw thanks for this project it's an awesome resssource
